// <auto-generated />
namespace ITSupport.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202304110419131_add-changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
